[package] 
name = "dragonling"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Colin Jacobs"]
license = "MIT"
description = "Dungeons & Dragons 5E module template."
repository = "https://github.com/coljac/typst-dnd5e"
keywords = ["roleplaying", "D&D", "Dungeons & Dragons"]
