# File containing English strings

language = "it"

[stats]
ac = "Classe Armatura"
hp = "Punti Ferita"
speed = "Velocità"

[sections]
actions = "Azioni"
reactions = "Reazioni"
limited_usage = "Uso Limitato"
equip = "Equipaggiamento"
legendary_act = "Azioni Leggendarie"